spring:
  rabbitmq:
    host: 192.168.65.140
    port: 5672
    username: root
    password: root
  cloud:
    config:
      override-none: true
  application:
    name: item-service
    
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka